version: '3.8'

services:
  mongo:
    container_name: congcong-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: congcong
    ports:
      - 27019:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
  api:
    driver: local